Repository dogecoin/dogecoin, pull requests merged in 2020-07, with the labels that each got.

#1548 Update README.md
  README.md
Labels: documentation

#1605 Get rid of git merge leftover text
  doc/release-notes.md
Labels: documentation

#1618 Fix links
  README.md
Labels: documentation

#1388 Articols matter in Italian
  src/qt/locale/bitcoin_it.ts
Labels: UI

#1626 httpserver: include deque
  src/httpserver.cpp
Labels: bug

#1629 Fix dogecoin payment links
  src/qt/paymentserver.cpp
Labels: bug
