Repository dogecoin/dogecoin, pull requests merged in 2021-07, with the labels that each got.

#2235 fix runtime for dogecoin on Alpine Linux (musl libc)
  src/crypto/scrypt.cpp
Labels: bug

#2393 [CI] add macOS GH Actions w/ bionic instead of focal
  .github/workflows/ci.yml
Labels: QA

#2392 [depends] Update osslsigncode mirror consistently
  contrib/gitian-descriptors/gitian-win-signer.yml
  doc/release-process.md
Labels: bug

#2380 Tune codeql-analysis
  .github/workflows/codeql-analysis.yml
Labels: QA

#1904 Snap Support
  .gitignore
  contrib/README.md
  contrib/snap/README.md
  contrib/snap/snapcraft.yaml
Labels: enhancement

#2217 Fix errors of bitcoin_ko_KR.ts file for 1.14.4-dev
  src/qt/locale/bitcoin_ko_KR.ts
Labels: UI, help wanted

#2325 depends: Update libevent to 2.1.11
  depends/packages/libevent.mk
Labels: do not merge yet

#2410 [ci] make dogecoin-qt builds explicit
  .github/workflows/ci.yml
Labels: QA

#2413 Correct #2342 - "added requirements to dependencies build README"
  depends/README.md
Labels: documentation

#2308 [QT] Add tips section
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
Labels: UI, enhancement

#2418 initialize fixed seeds
  src/chainparams.cpp
Labels: bug

#2420 Fix RPC port documentation in RPC help
  src/rpc/server.cpp
Labels: documentation

#1941 Fixing indonesian (id_ID) translation
  src/qt/locale/bitcoin_id_ID.ts
Labels: help wanted

#2236 Utils and libraries: Update ZMQ to 4.3.4
  depends/packages/zeromq.mk
  depends/patches/zeromq/0002-disable-pthread_set_name_np.patch
  depends/patches/zeromq/9114d3957725acd34aa8b8d011585812f3369411.patch
  depends/patches/zeromq/9e6745c12e0b100cd38acecc16ce7db02905e27c.patch
  depends/patches/zeromq/clock-unused-nsecs.patch
  depends/patches/zeromq/remove_libstd_link.patch
  depends/patches/zeromq/trusty-add-win32-inethdr.patch
Labels: dependencies, gitian check needed

#2249 1.14 fix magic numbers
  src/key.cpp
  src/pubkey.cpp
  src/pubkey.h
Labels: enhancement

#2422 test: Fixup replace-by-fee values
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/replace-by-fee.py
Labels: bug

#2423 [qa] reduce CodeQL triggers to exclude non-compiled code
  .github/workflows/codeql-analysis.yml
Labels: QA

#2368 1.14.4 fees
  qa/rpc-tests/fundrawtransaction.py
  qa/rpc-tests/test_framework/mininode.py
  src/Makefile.am
  src/dogecoin-fees.cpp
  src/dogecoin-fees.h
  src/dogecoin.cpp
  src/dogecoin.h
  src/init.cpp
  src/net_processing.cpp
  src/primitives/transaction.h
  src/qt/sendcoinsdialog.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: enhancement
