Repository dogecoin/dogecoin, pull requests merged in 2021-06, with the labels that each got.

#2238 Stop sending a Bitcoin alert to Dogecoin clients
  src/net_processing.cpp
Labels: bug

#2243 Qt: Add sortable sent/recv bytes to Peers debug table
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/peertablemodel.cpp
  src/qt/peertablemodel.h
Labels: UI, enhancement

#1825 [QT] Add a form dialog for adding peers
  src/Makefile.qt.include
  src/qt/forms/addpeerdialog.ui
  src/qt/forms/debugwindow.ui
  src/qt/forms/testpeerdialog.ui
  src/qt/peerdialog.cpp
  src/qt/peerdialog.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: enhancement

#2248 Change count type used by `gettxoutsetinfo`
  src/core_io.h
  src/core_write.cpp
  src/node/coinstats.h
  src/test/rpc_tests.cpp
Labels: enhancement

#2320 [CI] Switch 1.14.4 automated integration testing to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: QA

#2322 [CI] Enable windows unit tests
  .github/workflows/ci.yml
Labels: QA

#2341 [qa] Retain binary artifacts on CI run
  .github/workflows/ci.yml
Labels: QA

#2345 [qa] Make GH Actions CI less trigger happy
  .github/workflows/ci.yml
Labels: QA
