Repository dogecoin/dogecoin, pull requests merged in 2021-08, with the labels that each got.

#2428 Add build and setup instructions for NixOS
  contrib/nixos/shell.nix
  doc/build-unix.md
Labels: documentation

#2434 bugfix: break ActivateBestChain() differently on shutdown
  src/validation.cpp
Labels: bug

#2415 Reduce BIP125 replace by fee increment value
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/bumpfee.py
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.h
Labels: enhancement

#2348 [fees] introduce configurable hard dust limit
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/harddustlimit.py
  src/init.cpp
  src/policy/policy.cpp
  src/policy/policy.h
  src/primitives/transaction.h
  src/wallet/test/wallet_tests.cpp
Labels: enhancement

#2417 Reduce getheaders spam by serializing getheader requests per peer
  src/net.cpp
  src/net.h
  src/net_processing.cpp
Labels: bug

#2437 Adding startup logic where -paytxfee if lower than default, mintxfee is overridden
  src/wallet/wallet.cpp
Labels: enhancement

#2447 qt: translate all user-exposed strings
  src/qt/bitcoin.cpp
  src/qt/intro.cpp
  src/qt/peerdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/transactiondesc.cpp
  src/qt/utilitydialog.cpp
Labels: UI

#2448 qa: fix p2p-acceptblock
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p-acceptblock.py
  qa/rpc-tests/test_framework/blocktools.py
Labels: QA

#2451 rpc: add feefilter to peers from getpeerinfo
  src/net.cpp
  src/net.h
  src/rpc/net.cpp
Labels: enhancement

#2450 qa: txn_dblspend - fix arithmetic
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/txn_doublespend.py
Labels: QA

#2453 contrib: fix generate-seeds.py to use Dogecoin p2p ports
  contrib/seeds/generate-seeds.py
Labels: bug

#2446 Fix -paytxfee - episode 2
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/bumpfee.py
  qa/rpc-tests/paytxfee.py
  src/wallet/wallet.cpp
Labels: bug, QA

#2457 1.14.4 suggested changes for 2297
  src/validation.cpp
Labels: bug

#2441 1.14.4 fees disable rounding
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/feelimit.py
  qa/rpc-tests/test_framework/util.py
  src/amount.cpp
  src/amount.h
  src/dogecoin-fees.cpp
  src/miner.cpp
  src/test/amount_tests.cpp
  src/test/miner_tests.cpp
  src/validation.cpp
Labels: enhancement

#2458 Test that peers building on invalid blocks get disconnected
  qa/rpc-tests/p2p-acceptblock.py
  qa/rpc-tests/test_framework/mininode.py
Labels: QA

#2466 Update README.md, introduce INSTALL.md and doc/FAQ.md
  INSTALL.md
  README.md
  doc/FAQ.md
Labels: documentation

#2465 Update Unix build instructions
  doc/build-archlinux.md
  doc/build-fedora.md
  doc/build-freebsd.md
  doc/build-nixos.md
  doc/build-openbsd.md
  doc/build-unix.md
Labels: documentation

#2468 Update manpages for release
  doc/man/dogecoin-cli.1
  doc/man/dogecoin-qt.1
  doc/man/dogecoin-tx.1
  doc/man/dogecoind.1
Labels: documentation

#2479 snap packaging for 1.14.5
  contrib/snap/README.md
  contrib/snap/snapcraft.yaml
Labels: enhancement

#2487 Fix compiler warnings
  src/dogecoin-fees.cpp
  src/rpc/mining.cpp
  src/wallet/wallet.cpp
Labels: bug

#2490 Change key derivation path to be correct for Dogecoin
  qa/rpc-tests/wallet-hd.py
  src/wallet/wallet.cpp
Labels: bug

#2488 Grammatical: Added "," in #156
  CONTRIBUTING.md
Labels: documentation

#2497 1.14: Remove redundant explicitly defined copy constructors
  src/amount.h
  src/txmempool.cpp
  src/txmempool.h
Labels: bug
