Repository dogecoin/dogecoin, pull requests merged in 2021-12, with the labels that each got.

#2727 backport: Fail instead of truncate command name in CMessageHeader constructor
  src/protocol.cpp
  src/protocol.h
Labels: backport

#2687 [feat] Added ARMv8 SHA support
  .github/workflows/ci.yml
  configure.ac
  src/crypto/sha1.cpp
  src/crypto/sha256.cpp
  src/crypto/sha512.cpp
Labels: enhancement

#2755 rpc: Fix data race (UB) in InterruptRPC()
  src/rpc/server.cpp
Labels: bug, backport

#2759 net: avoid uninitialized reads on counters
  src/net.cpp
  src/net.h
Labels: enhancement, backport

#2757 net: Ensure every CNetAddr constructor initializes the scopeId field
  src/netaddress.cpp
  src/netaddress.h
  src/test/net_tests.cpp
Labels: bug, backport

#2756 Avoid leaking locktime fingerprint when anti-fee-sniping
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/txn_clone.py
  qa/rpc-tests/wallet_create_tx.py
  src/wallet/wallet.cpp
Labels: enhancement, backport

#2768 bench: add scrypt
  src/Makefile.bench.include
  src/bench/scrypt.cpp
Labels: enhancement
