Repository dogecoin/dogecoin, pull requests merged in 2021-02, with the labels that each got.

#1734 Fixate BIP65 softfork heights
  src/chainparams.cpp
  src/consensus/params.h
  src/rpc/blockchain.cpp
  src/validation.cpp
Labels: consensus

#1676 Don't recompute AuxPoW when serving peer requests
  src/chain.cpp
  src/chain.h
  src/net_processing.cpp
  src/validation.cpp
  src/validation.h
Labels: enhancement

#1741 Docs Update build-osx.md for Mac install
  doc/build-osx.md
Labels: documentation

#1774 Improve README.md
  README.md
Labels: documentation

#1775 1.14.3 release notes fix
  doc/release-notes.md
Labels: documentation
