Repository dogecoin/dogecoin, pull requests merged in 2021-11, with the labels that each got.

#2492 1.14.5 release notes
  doc/release-notes.md
  doc/release-notes/release-notes-1.14.4.md
Labels: documentation

#2653 rpc: improve error message in submitblock
  src/rpc/mining.cpp
Labels: enhancement

#2654 [rpc] configure auxpow rpc methods to use Namecoin-compatible API
  qa/rpc-tests/createauxblock.py
  qa/rpc-tests/getauxblock.py
  src/init.cpp
  src/rpc/mining.cpp
  src/rpc/server.h
Labels: enhancement

#2491 [feat] Added AVX2 SHA support
  .github/workflows/ci.yml
  configure.ac
  depends/Makefile
  depends/packages/intel-ipsec-mb.mk
  depends/packages/native_nasm.mk
  depends/packages/packages.mk
  depends/patches/intel-ipsec-mb/remove_digest_init.patch
  src/crypto/sha1.cpp
  src/crypto/sha256.cpp
  src/crypto/sha512.cpp
Labels: enhancement, gitian check needed

#2658 Update manpages for 1.14.5
  doc/man/dogecoin-cli.1
  doc/man/dogecoin-qt.1
  doc/man/dogecoin-tx.1
  doc/man/dogecoind.1
Labels: documentation

#2661 doc: write out the fee recommendation
  doc/fee-recommendation.md
Labels: documentation

#2666 Give QApplication dummy arguments
  src/qt/bitcoin.cpp
  src/qt/test/test_main.cpp
Labels: bug

#2659 trivial: remove empty pixmap tag in overviewpage.ui
  src/qt/forms/overviewpage.ui
Labels: UI

#2664 doc: backport reduce-memory.md from 1.21-dev
  doc/reduce-memory.md
Labels: documentation

#2668 doc: backport files.md that describes the data directory
  doc/files.md
Labels: documentation

#2673 security: Backport madvise() for lockedpool sensitive data from 1.21-dev
  src/support/lockedpool.cpp
Labels: bug

#2671 doc: add link to fee recommendation
  README.md
Labels: documentation

#2568 Docs4Doge : create "getting started" section
  README.md
  doc/README.md
  doc/getting-started.md
Labels: documentation

#2667 Update and clarify 1.14.5 release notes
  doc/release-notes.md
Labels: documentation

#2682 qa: fixup codeql path scope
  .github/workflows/codeql-analysis.yml
Labels: QA

#2683 qa: nuke caches on CI descriptor change
  .github/workflows/ci.yml
Labels: QA

#2685 qa: fix race condition in p2p-policy test
  qa/rpc-tests/p2p-policy.py
Labels: QA

#2692 doc: fix capitalization
  README.md
Labels: documentation

#2694 bench: remove erroring components and integrate with CI
  .github/workflows/ci.yml
  src/Makefile.bench.include
Labels: QA

#2693 build: change minimum boost to 1_60_0
  configure.ac
  src/test/scheduler_tests.cpp
  src/utiltime.cpp
Labels: dependencies

#2660 [qa] run the experimental builds on bionic too
  .github/workflows/ci.yml
Labels: QA

#2716 Fix typo in docs when checking shasum
  doc/build-unix.md
Labels: documentation

#2561 1.21 auxpow header
  src/Makefile.am
  src/auxpow.cpp
  src/auxpow.h
  src/chain.cpp
  src/primitives/block.cpp
  src/primitives/block.h
Labels: consensus
