Repository dogecoin/dogecoin, pull requests merged in 2021-05, with the labels that each got.

#1976 Travis: switch back to trusty and remove useless repos
  .travis.yml
Labels: QA

#1856 Qt Add GUI wif import dialog
  contrib/bitcoin-qt.pro
  src/Makefile.qt.include
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/importkeysdialog.ui
  src/qt/importkeysdialog.cpp
  src/qt/importkeysdialog.h
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: enhancement

#1908 Qt: Show only useful estimates on sync screen
  src/qt/modaloverlay.cpp
Labels: UI, enhancement

#2115 Sync nodes before maturing blocks in bumpfee
  test/functional/wallet_bumpfee.py
Labels: bug

#1869 Add functionality to generate auxpow blocks in regtest
  .gitignore
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/test/rpc_tests.cpp
Labels: enhancement

#2154 depends: update Qt 5.9 source url
  depends/packages/qt.mk
Labels: bug

#1990 1.21 Replace checkpoints with Dogecoin chains
  src/chainparams.cpp
Labels: consensus

#2198 Disable CSV and SegWit on Dogecoin
  src/chainparams.cpp
Labels: consensus

#2203 1.21 Update min chain work and assume valid
  src/chainparams.cpp
Labels: consensus

#2204 Replace feature enablement blocks
  src/chainparams.cpp
Labels: consensus

#1977 1.21 Introduce Dogecoin difficulty calculations
  src/Makefile.am
  src/Makefile.test.include
  src/dogecoin.cpp
  src/dogecoin.h
  src/pow.cpp
  src/test/dogecoin_tests.cpp
Labels: consensus

#2210 Introduce Dogecoin block subsidy calculations
  src/chainparams.cpp
  src/consensus/params.h
  src/dogecoin.cpp
  src/dogecoin.h
  src/miner.cpp
  src/qt/test/rpcnestedtests.cpp
  src/rpc/blockchain.cpp
  src/test/blockfilter_index_tests.cpp
  src/test/dogecoin_tests.cpp
  src/test/validation_block_tests.cpp
  src/test/validation_tests.cpp
  src/validation.cpp
  src/wallet/test/wallet_tests.cpp
  test/functional/data/rpc_getblockstats.json
  test/functional/feature_block.py
  test/functional/feature_csv_activation.py
  test/functional/feature_segwit.py
  test/functional/interface_bitcoin_cli.py
  test/functional/interface_rest.py
  test/functional/mempool_reorg.py
  test/functional/mempool_resurrect.py
  test/functional/mempool_spend_coinbase.py
  test/functional/p2p_blocksonly.py
  test/functional/p2p_invalid_block.py
  test/functional/p2p_tx_download.py
  test/functional/rpc_blockchain.py
  test/functional/rpc_createmultisig.py
  test/functional/rpc_dumptxoutset.py
  test/functional/rpc_fundrawtransaction.py
  test/functional/rpc_getblockstats.py
  test/functional/rpc_psbt.py
  test/functional/rpc_rawtransaction.py
  test/functional/test_framework/blocktools.py
  test/functional/wallet_backup.py
  test/functional/wallet_balance.py
  test/functional/wallet_basic.py
  test/functional/wallet_importdescriptors.py
  test/functional/wallet_labels.py
  test/functional/wallet_listtransactions.py
  test/functional/wallet_multiwallet.py
  test/functional/wallet_send.py
  test/functional/wallet_txn_clone.py
  test/functional/wallet_txn_doublespend.py
  test/lint/lint-includes.sh
Labels: consensus
