Repository dogecoin/dogecoin, pull requests merged in 2021-09, with the labels that each got.

#2485 1.14.5 fees
  qa/rpc-tests/abandonconflict.py
  qa/rpc-tests/bumpfee.py
  qa/rpc-tests/fundrawtransaction.py
  qa/rpc-tests/importprunedfunds.py
  qa/rpc-tests/paytxfee.py
  qa/rpc-tests/prioritise_transaction.py
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/txn_doublespend.py
  qa/rpc-tests/wallet.py
  src/amount.cpp
  src/dogecoin-fees.cpp
  src/miner.cpp
  src/policy/policy.h
  src/test/amount_tests.cpp
  src/test/miner_tests.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.h
Labels: do not merge yet

#2502 update freebsd build docs
  doc/build-freebsd.md
Labels: documentation

#2515 french translations update (sync with Dogecoin instead Bitcoin network)
  src/qt/locale/bitcoin_fr.ts
Labels: UI

#2503 Fix implicit switch fallthrough warnings
  src/hash.cpp
  src/qt/rpcconsole.cpp
  src/rest.cpp
  src/rpc/mining.cpp
  src/tinyformat.h
Labels: bug

#2570 Docs4Doge : refresh README.md introduction sentence
  README.md
Labels: documentation

#2567 Replace smart fee UI with predefined fees
  src/dogecoin-fees.cpp
  src/dogecoin-fees.h
  src/qt/forms/sendcoinsdialog.ui
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsdialog.h
  src/wallet/coincontrol.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: UI

#2581 depends: Update OpenSSL to 1.0.2u and fix issues it introduces
  depends/Makefile
  depends/hosts/darwin.mk
  depends/packages/openssl.mk
  depends/patches/openssl/secure_getenv.patch
Labels: dependencies

#2500 Fix self-assigned nVersion in CAlert serialization
  src/alert.h
Labels: bug

#2595 build: Add libxkbcommon 0.8.4
  contrib/devtools/symbol-check.py
  contrib/gitian-descriptors/gitian-linux.yml
  depends/README.md
  depends/packages/libxkbcommon.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
Labels: backport, dependencies
