Repository dogecoin/dogecoin, pull requests merged in 2021-10, with the labels that each got.

#2501 Harmonize CI and Gitian to use the same toolchain
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  configure.ac
  contrib/devtools/symbol-check.py
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
  depends/packages/zeromq.mk
  depends/patches/zeromq/trusty-add-win32-inethdr.patch
  src/Makefile.am
  src/compat/glibc_compat.cpp
  src/init.cpp
Labels: enhancement, QA, gitian check needed

#2605 qa: facilitate MIN_CHANGE to be higher than COIN in tests
  qa/rpc-tests/fundrawtransaction.py
  qa/rpc-tests/importprunedfunds.py
  src/wallet/test/wallet_tests.cpp
Labels: QA

#2606 Split the dust definition 3-way to enable lower limits
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/bumpfee.py
  qa/rpc-tests/p2p-policy.py
  src/dogecoin-fees.cpp
  src/dogecoin-fees.h
  src/init.cpp
  src/policy/policy.cpp
  src/policy/policy.h
  src/primitives/transaction.h
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/paymentserver.cpp
  src/test/transaction_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: major rework

#2608 fees: Make wallet minimum change parameters dynamic
  src/qt/coincontroldialog.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: enhancement

#2627 Call va_end() on va_started() args
  src/zmq/zmqpublishnotifier.cpp
Labels: bug

#2628 univalue: update to latest version
  contrib/devtools/commit-script-check.sh
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/protocol.cpp
  src/rpc/rawtransaction.cpp
  src/test/data/base58_keys_invalid.json
  src/test/data/base58_keys_valid.json
  src/test/data/tt-delin1-out.json
  src/test/data/tt-delout1-out.json
  src/test/data/tt-locktime317000-out.json
  src/test/data/txcreate1.json
  src/test/data/txcreatedata1.json
  src/test/data/txcreatedata2.json
  src/test/data/txcreatedata_seq1.json
  src/test/data/txcreatemultisig1.json
  src/univalue/.cirrus.yml
  src/univalue/.travis.yml
  src/univalue/Makefile.am
  src/univalue/README
  src/univalue/README.md
  src/univalue/build-aux/m4/ax_cxx_compile_stdcxx.m4
  src/univalue/configure.ac
  src/univalue/gen/gen.cpp
  src/univalue/include/univalue.h
  src/univalue/lib/univalue.cpp
  src/univalue/lib/univalue_escapes.h
  src/univalue/lib/univalue_get.cpp
  src/univalue/lib/univalue_read.cpp
  src/univalue/lib/univalue_utffilter.h
  src/univalue/lib/univalue_write.cpp
  src/univalue/sources.mk
  src/univalue/test/.gitignore
  src/univalue/test/fail1.json
  src/univalue/test/fail42.json
  src/univalue/test/fail44.json
  src/univalue/test/fail45.json
  src/univalue/test/no_nul.cpp
  src/univalue/test/object.cpp
  src/univalue/test/pass4.json
  src/univalue/test/round3.json
  src/univalue/test/round4.json
  src/univalue/test/round5.json
  src/univalue/test/round6.json
  src/univalue/test/round7.json
  src/univalue/test/test_json.cpp
  src/univalue/test/unitester.cpp
  src/wallet/rpcwallet.cpp
Labels: dependencies

#2629 qa: fixes pruning test
  qa/rpc-tests/pruning.py
  src/net_processing.cpp
  src/net_processing.h
Labels: QA

#2645 [rpc] Add dustlimit info to getnetworkinfo
  qa/rpc-tests/dustlimits.py
  src/rpc/net.cpp
Labels: enhancement

#2286 Shut down if trying to connect a corrupted block
  src/validation.cpp
Labels: enhancement
