Repository dogecoin/dogecoin, pull requests merged in 2022-06, with the labels that each got.

#2968 Create README_pt_BR.md
  README_pt_BR.md
Labels: documentation

#2798 Update README_zh_CN.md
  README_zh_CN.md
Labels: documentation, help wanted

#2970 Added Persian translation of README.md file
  README_fa_IR.md
Labels: documentation

#2978 ci: force remove mono from windows builds
  .github/workflows/ci.yml
Labels: QA, urgent

#2976 qa: add tests for `addr` messages
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p-addr.py
  qa/rpc-tests/test_framework/mininode.py
Labels: QA

#2986 net: implement a mockable micro time
  src/net_processing.cpp
  src/utiltime.cpp
  src/utiltime.h
Labels: enhancement

#2934 Retain traffic graph values
  src/qt/trafficgraphwidget.cpp
  src/qt/trafficgraphwidget.h
Labels: UI

#2936 Depends: Update zlib to 1.2.12
  depends/packages/zlib.mk
Labels: dependencies

#2758 net: Introduce a maximum size for locators
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p_invalid_locator.py
  qa/rpc-tests/test_framework/mininode.py
  src/net.h
  src/net_processing.cpp
Labels: enhancement, backport

#2991 Remove alert system
  src/Makefile.am
  src/Makefile.test.include
  src/alert.cpp
  src/alert.h
  src/chainparams.cpp
  src/chainparams.h
  src/init.cpp
  src/net.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/test/alert_tests.cpp
  src/test/data/alertTests.raw
  src/ui_interface.h
  src/validation.cpp
  src/validation.h
  src/warnings.cpp
Labels: cleanup

#2994 qa: remove test-local dependencies on enable_mocktime
  qa/rpc-tests/listtransactions.py
  qa/rpc-tests/receivedby.py
Labels: QA, urgent

#2988 Add an RPC method showing wallet transactions that are not in the mempool
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/liststucktransactions.py
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: enhancement

#2996 Add configurable backup directory for wallet dumps and backups
  qa/rpc-tests/wallet-dump.py
  qa/rpc-tests/wallet-hd.py
  qa/rpc-tests/walletbackup.py
  src/Makefile.am
  src/bitcoin-cli.cpp
  src/init.cpp
  src/util.cpp
  src/util.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcutil.cpp
  src/wallet/rpcutil.h
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
Labels: enhancement

#3000 Force `verifychain` RPC args to be positive
  qa/rpc-tests/blockchain.py
  src/rpc/blockchain.cpp
Labels: enhancement

#2973 Improved gitian build script
  contrib/gitian-build.sh
  doc/gitian-building.md
Labels: documentation

#2995 doc: maintain the biplist
  doc/bips.md
Labels: documentation

#2997 net: constrain the memory usage of manually added nodes
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/addnode.py
  src/net.cpp
  src/qt/peerdialog.cpp
  src/rpc/net.cpp
  src/rpc/protocol.h
Labels: enhancement

#3003 qa: harden the p2p-policy test
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p-policy.py
Labels: QA, urgent

#2998 improve some user-facing strings
  src/init.cpp
  src/qt/coincontroldialog.cpp
  src/qt/forms/importkeysdialog.ui
  src/qt/forms/sendcoinsdialog.ui
  src/qt/overviewpage.cpp
Labels: UI

#3009 locale: update the strings and english translation files
  src/qt/bitcoinstrings.cpp
  src/qt/locale/bitcoin_en.ts
Labels: UI, urgent

#3010 locale: update recent translations
  src/qt/locale/bitcoin_fa.ts
  src/qt/locale/bitcoin_fr.ts
  src/qt/locale/bitcoin_id_ID.ts
  src/qt/locale/bitcoin_it.ts
  src/qt/locale/bitcoin_ko_KR.ts
  src/qt/locale/bitcoin_nl.ts
  src/qt/locale/bitcoin_ta.ts
Labels: UI, urgent

#3011 locale: update languages that have no recent updates
  src/qt/locale/bitcoin_af.ts
  src/qt/locale/bitcoin_ar.ts
  src/qt/locale/bitcoin_be_BY.ts
  src/qt/locale/bitcoin_bg.ts
  src/qt/locale/bitcoin_ca.ts
  src/qt/locale/bitcoin_cs.ts
  src/qt/locale/bitcoin_cy.ts
  src/qt/locale/bitcoin_da.ts
  src/qt/locale/bitcoin_de.ts
  src/qt/locale/bitcoin_el.ts
  src/qt/locale/bitcoin_en_GB.ts
  src/qt/locale/bitcoin_eo.ts
  src/qt/locale/bitcoin_es.ts
  src/qt/locale/bitcoin_et.ts
  src/qt/locale/bitcoin_eu_ES.ts
  src/qt/locale/bitcoin_fi.ts
  src/qt/locale/bitcoin_gl.ts
  src/qt/locale/bitcoin_he.ts
  src/qt/locale/bitcoin_hi_IN.ts
  src/qt/locale/bitcoin_hr.ts
  src/qt/locale/bitcoin_hu.ts
  src/qt/locale/bitcoin_ja.ts
  src/qt/locale/bitcoin_ka.ts
  src/qt/locale/bitcoin_kk_KZ.ts
  src/qt/locale/bitcoin_ku_IQ.ts
  src/qt/locale/bitcoin_ky.ts
  src/qt/locale/bitcoin_la.ts
  src/qt/locale/bitcoin_lt.ts
  src/qt/locale/bitcoin_lv_LV.ts
  src/qt/locale/bitcoin_mk_MK.ts
  src/qt/locale/bitcoin_mn.ts
  src/qt/locale/bitcoin_ms_MY.ts
  src/qt/locale/bitcoin_nb.ts
  src/qt/locale/bitcoin_ne.ts
  src/qt/locale/bitcoin_pl.ts
  src/qt/locale/bitcoin_pt_BR.ts
  src/qt/locale/bitcoin_pt_PT.ts
  src/qt/locale/bitcoin_ro.ts
  src/qt/locale/bitcoin_ru.ts
  src/qt/locale/bitcoin_sk.ts
  src/qt/locale/bitcoin_sl_SI.ts
  src/qt/locale/bitcoin_sq.ts
  src/qt/locale/bitcoin_sr.ts
  src/qt/locale/bitcoin_sr@latin.ts
  src/qt/locale/bitcoin_sv.ts
  src/qt/locale/bitcoin_th_TH.ts
  src/qt/locale/bitcoin_tr.ts
  src/qt/locale/bitcoin_uk.ts
  src/qt/locale/bitcoin_ur_PK.ts
  src/qt/locale/bitcoin_uz@Cyrl.ts
  src/qt/locale/bitcoin_vi.ts
  src/qt/locale/bitcoin_zh_CN.ts
  src/qt/locale/bitcoin_zh_TW.ts
Labels: UI, urgent

#2974 Add rescan RPC command
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/rescan.py
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: enhancement

#2964 Set the wallet's discard threshold to 0.01 DOGE
  doc/fee-recommendation.md
  qa/rpc-tests/bumpfee.py
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.h
Labels: enhancement, documentation

#3015 Improve data types for network data
  src/httpserver.cpp
  src/netbase.cpp
  src/netbase.h
  src/test/netbase_tests.cpp
Labels: cleanup
