Repository dogecoin/dogecoin, pull requests merged in 2022-10, with the labels that each got.

#3080 qa: fix ltc-scrypt
  .github/workflows/ci.yml
  qa/README.md
  qa/pull-tester/install-deps.sh
Labels: bug, QA

#3127 build: explicitly disable libsecp256k1 openssl tests
  configure.ac
Labels: dependencies

#3135 Revert "crypto: added runtime checks for SHA hardware"
  configure.ac
  src/crypto/sha1.cpp
  src/crypto/sha1.h
  src/crypto/sha256.cpp
  src/crypto/sha256.h
  src/crypto/sha512.cpp
  src/crypto/sha512.h
  src/util.cpp
Labels: bug

#3126 qa: python implementation for ripemd160
  test/functional/test_framework/ripemd160.py
  test/functional/test_framework/script.py
Labels: backport, QA

#3137 Fix warning in dbwrapper test
  src/test/dbwrapper_tests.cpp
Labels: QA, cleanup

#3145 ci: drop extraneous libtinfo5 from x86_64-apple-darwin11
  .github/workflows/ci.yml
Labels: QA, cleanup

#3143 depends: tar: Always extract as yourself
  depends/funcs.mk
  depends/packages/native_cctools.mk
  depends/packages/qt.mk
Labels: enhancement, backport, dependencies

#3102 Add height to importpubkey for rescan
  qa/rpc-tests/import-rescan.py
  src/rpc/client.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
Labels: enhancement

#3147 qa: update ltc_scrypt installation script and documentation
  test/README.md
  test/functional/install-deps.sh
Labels: QA, dependencies

#3154 ci: fix gui selectors
  .github/workflows/ci.yml
Labels: QA

#3148 Update French translation
  src/qt/locale/bitcoin_fr.ts
Labels: UI

#3157 net: Avoiding C-style NUL-terminated strings in interfaces
  src/Makefile.am
  src/attributes.h
  src/httpserver.cpp
  src/init.cpp
  src/net.cpp
  src/netbase.cpp
  src/netbase.h
  src/qt/optionsdialog.cpp
  src/qt/rpcconsole.cpp
  src/rpc/net.cpp
  src/test/addrman_tests.cpp
  src/test/net_tests.cpp
  src/test/netbase_tests.cpp
  src/torcontrol.cpp
  src/utilstring.h
Labels: QA, cleanup
