Repository dogecoin/dogecoin, pull requests merged in 2022-02, with the labels that each got.

#2842 depends: change fallback to depends.dogecoincore.org
  depends/Makefile
  depends/funcs.mk
Labels: dependencies

#2843 qa: change download location and harden process for SDKs in CI
  .github/workflows/ci.yml
Labels: QA, dependencies

#2770 add blockhashbyheight to rest interface
  doc/REST-interface.md
  qa/rpc-tests/rest.py
  src/rest.cpp
Labels: enhancement

#2849 depends: port dependency location changes to 1.21
  ci/test/00_setup_env.sh
  depends/Makefile
  depends/funcs.mk
Labels: backport, dependencies

#2745 Add install_db5.sh and update build-unix
  build-aux/m4/dogecoin_find_bdb53.m4
  contrib/install_db5.sh
  doc/build-unix.md
Labels: backport
