Repository dogecoin/dogecoin, pull requests merged in 2022-07, with the labels that each got.

#2910 build: Fix warnings when running autogen.sh
  Makefile.am
  src/Makefile.am
  src/Makefile.qt.include
Labels: backport, gitian check needed

#3022 Update bitcoin_ko_KR.ts for 1.14.6 dev
  src/qt/locale/bitcoin_ko_KR.ts
Labels: UI

#2409 depends: libevent 2.1.12-stable
  depends/packages/libevent.mk
  depends/patches/libevent/glibc_compatibility.patch
Labels: backport, dependencies

#3014 Updated italian phrases for 1.14.6 release.
  src/qt/locale/bitcoin_it.ts
Labels: UI

#3030 net: rework transaction download scheduling
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p-tx-download.py
  qa/rpc-tests/test_framework/mininode.py
  src/net.cpp
  src/net.h
  src/net_processing.cpp
Labels: bug, backport

#3035 Draft release notes for 1.14.6
  doc/release-notes.md
  doc/release-notes/release-notes-1.14.5.md
Labels: documentation, urgent

#3034 doc: clean up fee-recommendation.md for 1.14.6
  doc/fee-recommendation.md
Labels: documentation

#3033 doc: crosslink the translated readme files
  README.md
  README_fa_IR.md
  README_pt_BR.md
  README_zh_CN.md
Labels: documentation

#3008 net: rate limit the processing of incoming addr messages
  qa/rpc-tests/p2p-addr.py
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/rpc/net.cpp
Labels: enhancement, backport

#3037 Make IPC server names unique per server
  src/qt/paymentserver.cpp
Labels: cleanup

#3038 net: update mainnet seeds
  src/chainparamsseeds.h
Labels: cleanup

#3043 release notes: add section about pruning in Qt
  doc/release-notes.md
Labels: documentation, urgent

#3044 release notes: bring back mailing list
  doc/release-notes.md
Labels: documentation, urgent

#3046 Enhance release notes
  doc/release-notes.md
Labels: documentation, urgent

#3042 Update the linux custom build guides
  doc/build-archlinux.md
  doc/build-fedora.md
Labels: documentation

#3026 Minor updates to Dutch translation
  src/qt/locale/bitcoin_nl.ts
Labels: UI

#3029 Minor updates to portuguese from portugal translation (1.14.6-dev)
  src/qt/locale/bitcoin_pt_PT.ts
Labels: UI

#3047 release notes: minor changes
  doc/release-notes.md
Labels: documentation, urgent

#3036 Update bitcoin_bg.ts - Български
  src/qt/locale/bitcoin_bg.ts
Labels: UI, urgent

#3057 open 1.14.7-dev for development
  configure.ac
  src/clientversion.h
Labels: urgent

#3063 qt: Rename signals for peer dialog
  src/qt/peerdialog.cpp
  src/qt/peerdialog.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: bug, UI

#3070 RPC row added to "such ports" table
  README_zh_CN.md
Labels: documentation

#2773 Fix and enable scrypt sse2 integration
  .github/workflows/ci.yml
  configure.ac
  src/Makefile.am
  src/crypto/scrypt.cpp
  src/crypto/scrypt.h
  src/init.cpp
Labels: bug

#3066 Fix invalid settings in dogecoind.service
  contrib/init/dogecoind.service
Labels: bug

#3025 ci: added qemu ARM executable testing
  .github/workflows/ci.yml
Labels: QA

#3076 remove openssl header includes in scrypt sources
  src/crypto/scrypt-sse2.cpp
  src/crypto/scrypt.cpp
Labels: cleanup

#3077 New PR for #3060
  README.md
  README_fa_IR.md
  README_pt_BR.md
  README_vi_VN.md
  README_zh_CN.md
Labels: documentation

#3081 qa: backports pure python ripemd160
  qa/rpc-tests/segwit.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/ripemd160.py
  qa/rpc-tests/test_framework/script.py
Labels: backport, QA
