Repository dogecoin/dogecoin, pull requests merged in 2022-01, with the labels that each got.

#2779 Partial Translations for Korean
  src/qt/locale/bitcoin_ko_KR.ts
Labels: UI, help wanted

#2765 Fix Char as Bool in interfaces
  src/wallet/wallet.h
Labels: backport

#2778 Fix QT high DPI scaling
  src/qt/bitcoin.cpp
Labels: bug
