Repository dogecoin/dogecoin, pull requests merged in 2022-04, with the labels that each got.

#2907 qa: remove experimental ci for aarch64 sha512
  .github/workflows/ci.yml
Labels: QA

#2869 Fixing Persian Translation; mainly repalcing Bitcoin with Dogecoin
  src/qt/locale/bitcoin_fa.ts
Labels: UI, do not merge yet

#2860 [qa] fix binary response parsing in rest test
  qa/rpc-tests/rest.py
Labels: QA

#2754 Network Tab Maximum Granularity.
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/peertablemodel.cpp
Labels: UI

#2870 Add lupdate to translation policy
  doc/translation_strings_policy.md
  src/Makefile.qt.include
Labels: documentation

#2923 Qt: Add prune setting to OptionsDialog
  src/qt/forms/optionsdialog.ui
  src/qt/guiconstants.h
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
Labels: enhancement, UI, backport

#2909 fix rest/getutxos endpoint for usage without mempool
  qa/rpc-tests/rest.py
  src/rest.cpp
Labels: bug

#2882 build: work around ubuntu:focal libgcc-9-dev-arm64-cross issue
  .github/workflows/ci.yml
  src/compat/arm_acle_patched.h
  src/compat/arm_acle_selector.h
  src/crypto/sha1.cpp
  src/crypto/sha256.cpp
  src/crypto/sha512.cpp
Labels: bug
