Repository dogecoin/dogecoin, pull requests merged in 2022-11, with the labels that each got.

#3136 distinguish experimental features and enforce explicit configuration of these
  .github/workflows/ci.yml
  CONTRIBUTING.md
  build-aux/m4/dogecoin_experimental.m4
  configure.ac
  doc/experiments.md
  src/Makefile.am
  src/crypto/scrypt-sse2.cpp
  src/crypto/sha1.cpp
  src/crypto/sha256.cpp
  src/crypto/sha512.cpp
  src/support/experimental.h
Labels: enhancement, documentation

#3140 ci: update actions libraries to node16
  .github/workflows/ci.yml
Labels: QA

#3158 fix: misnamed header file in Makefile.am
  src/Makefile.am
Labels: bug

#3141 depends: adds QT 5.7.1 'QFixed' context error patch
  depends/packages/qt.mk
  depends/patches/qt/fix_qfontengine_coretext.patch
Labels: dependencies

#3139 depends: update zlib to 1.2.13
  depends/packages/zlib.mk
Labels: dependencies

#3146 depends: only use explicit CC for mingw32 in intel-ipsec-mb
  depends/packages/intel-ipsec-mb.mk
Labels: bug, dependencies
