Repository dogecoin/dogecoin, pull requests merged in 2022-05, with the labels that each got.

#2937 Added declaration check for sha512 on armv82
  configure.ac
Labels: enhancement

#2698 Add RPC command to set max connection count
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/setmaxconnections.py
  src/init.cpp
  src/net.cpp
  src/net.h
  src/rpc/client.cpp
  src/rpc/net.cpp
Labels: enhancement

#2885 1.21: Update to Berkeley DB 5.3
  .cirrus.yml
  build-aux/m4/dogecoin_find_bdb53.m4
  ci/test/00_setup_env_i686_centos.sh
  ci/test/00_setup_env_mac_host.sh
  ci/test/00_setup_env_native_msan.sh
  ci/test/05_before_script.sh
  configure.ac
  contrib/install_db4.sh
  contrib/install_db5.sh
  depends/packages/bdb.mk
  depends/patches/bdb/clang_cxx_11.patch
  depends/patches/bdb/configure.patch
  depends/patches/bdb/winioctl.patch
  doc/build-freebsd.md
  doc/build-netbsd.md
  doc/build-openbsd.md
  doc/build-osx.md
  doc/build-unix.md
  doc/dependencies.md
  doc/productivity.md
Labels: backport

#2903 Complete update of the French translation file (bitcoin_fr.ts)
  src/qt/locale/bitcoin_fr.ts
Labels: UI

#2947 Dutch/Flamish Translation Update
  src/qt/locale/bitcoin_nl.ts
Labels: UI

#2807 Updating bitcoin_ko_KR.ts
  src/qt/locale/bitcoin_ko_KR.ts
Labels: UI

#2953 Changing sentence in UI that could suggest a private key is not 100% private
  src/qt/overviewpage.cpp
Labels: UI

#2971 Update bitcoin_ta.ts
  src/qt/locale/bitcoin_ta.ts
Labels: UI

#2954 doc: formalize pull request review timelines
  CONTRIBUTING.md
Labels: documentation
