Repository dogecoin/dogecoin, pull requests merged in 2022-08, with the labels that each got.

#3071 depends: Update intel-ipsec-mb to 1.2 for Win64
  .github/workflows/ci.yml
  configure.ac
  depends/packages/intel-ipsec-mb.mk
  depends/packages/native_nasm.mk
  depends/packages/packages.mk
  src/crypto/sha1.cpp
  src/crypto/sha256.cpp
  src/crypto/sha512.cpp
Labels: enhancement, dependencies

#3079 qa: remove openssl comparison from wallet test
  src/wallet/test/crypto_tests.cpp
Labels: cleanup

#3103 fix bugs in Chinese translation
  src/qt/locale/bitcoin_zh_CN.ts
Labels: UI

#3088 Fix: parse -maxtxfee outside of CWallet
  src/init.cpp
  src/wallet/wallet.cpp
Labels: bug
