Repository dogecoin/dogecoin, pull requests merged in 2023-10, with the labels that each got.

#3308 build: bdb detection and configuration fixes for macOs/brew
  build-aux/m4/dogecoin_find_bdb53.m4
  configure.ac
Labels: bug

#3355 ci: add linter for translations
  .github/workflows/linter.yml
Labels: QA

#3357 depends: updated to protobuf 3.6.1
  depends/packages/native_protobuf.mk
Labels: dependencies
