Repository dogecoin/dogecoin, pull requests merged in 2023-11, with the labels that each got.

#3345 depends: updated to zlib 1.3
  depends/packages/zlib.mk
Labels: dependencies

#3358 depends: reduce Qt footprint
  build-aux/m4/bitcoin_qt.m4
  contrib/devtools/symbol-check.py
  depends/packages/dbus.mk
  depends/packages/libX11.mk
  depends/packages/libXext.mk
  depends/packages/libxcb.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/xextproto.mk
  depends/packages/xtrans.mk
  depends/patches/qt/no-xlib.patch
Labels: dependencies

#3350 ci: disable macOs native task
  .cirrus.yml
Labels: QA

#3381 1.21-dev: fix for GCC13 compilation errors
  src/support/lockedpool.cpp
  src/util/bip32.h
  src/util/string.h
Labels: bug

#3380 Reduce CI false positives
  ci/test/00_setup_env.sh
  ci/test/00_setup_env_i686_centos.sh
  ci/test/05_before_script.sh
  test/functional/install-deps.sh
Labels: bug, QA

#3257 Add height parameter to walletnotify message
  src/wallet/wallet.cpp
Labels: enhancement

#3271 depends: expat 2.5.0
  depends/packages/expat.mk
Labels: dependencies

#3384 doc: added security update guidance
  INSTALL.md
  doc/build-unix.md
  doc/build-windows.md
Labels: documentation

#3383 ci: execute only one aarch64 experimental ci
  .github/workflows/ci.yml
Labels: QA

#3214 build: constrain -lQt5PlatformSupport check as AVX2 dependency
  configure.ac
Labels: cleanup
