Repository dogecoin/dogecoin, pull requests merged in 2024-02, with the labels that each got.

#3395 Update bitcoin_ko_KR.ts
  src/qt/locale/bitcoin_ko_KR.ts
Labels: UI

#3297 rpc: Add getblockstats
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/data/getblockstats.json
  qa/rpc-tests/getblockstats.py
  src/Makefile.am
  src/rpc/blockchain.cpp
  src/rpc/blockchain.h
  src/rpc/client.cpp
  src/test/rpc_tests.cpp
  src/validation.cpp
  src/validation.h
Labels: RPC

#2676 [Qt] Reduce font warnings
  src/qt/bitcoin.qrc
  src/qt/bitcoingui.cpp
  src/qt/optionsdialog.cpp
  src/qt/res/fonts/NotoSans-Bold.ttf
  src/qt/res/fonts/NotoSans-Light.ttf
  src/qt/res/fonts/NotoSans-Medium.ttf
  src/qt/res/fonts/NotoSans-Regular.ttf
Labels: UI

#3420 Add NotoSans font to Qt makefile includes
  src/Makefile.qt.include
Labels: bug, urgent

#3415 depends: backport Qt bugfixes
  depends/packages/qt.mk
  depends/patches/qt/backports-1.patch
Labels: bug, UI, dependencies

#3417 doc: list minimum os versions
  INSTALL.md
Labels: documentation

#2686 docs: update macos build guide
  INSTALL.md
  doc/Building-Dogecoin-1.14-for-Mac.md
  doc/build-macos.md
  doc/build-osx.md
Labels: documentation

#3419 add Chinese (zh_CN) translations to 1.14.7, full coverage
  src/qt/locale/bitcoin_zh_CN.ts
Labels: UI

#3427 qt: fix qt4 compile error
  src/qt/paymentserver.cpp
Labels: bug, UI

#3429 [QA] Check command-line arguments for test runner
  qa/pull-tester/rpc-tests.py
Labels: QA

#3423 doc: update manpages
  doc/man/dogecoin-cli.1
  doc/man/dogecoin-qt.1
  doc/man/dogecoin-tx.1
  doc/man/dogecoind.1
Labels: documentation

#3389 policy: tune feerate estimator parameters
  src/policy/fees.h
  src/test/policyestimator_tests.cpp
Labels: enhancement

#3430 Minor update bitcoin_ko_KR.ts
  src/qt/locale/bitcoin_ko_KR.ts
Labels: UI

#3195 Update and correction of French translation files (bitcoin_fr.ts,bitcoin_fr_CA.ts and bitcoin_fr_FR.ts)
  src/qt/locale/bitcoin_fr.ts
  src/qt/locale/bitcoin_fr_CA.ts
Labels: UI, help wanted

#3428 Minor Update of Italian Translation
  src/qt/locale/bitcoin_it.ts
Labels: UI, help wanted

#3382 qa: test walletnotify
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/walletnotify.py
Labels: QA

#3388 Backport Bitcoin's share/rpcauth/rpcauth.py in rpcuser.py
  share/rpcuser/rpcuser.py
Labels: enhancement

#3435 Translate dutch (nl)
  src/qt/locale/bitcoin_nl.ts
Labels: UI

#3444 doc: update debian/copyright
  contrib/debian/copyright
Labels: documentation

#3443 doc: document maturity of RPC methods
  doc/rpc-maturity.md
Labels: documentation

#3433 policy: only load fee_estimates.dat from 1.14.7 and later
  src/txmempool.cpp
  src/txmempool.h
Labels: enhancement

#3375 build: fix bdb detection with macOs/brew
  build-aux/m4/dogecoin_find_bdb53.m4
  configure.ac
Labels: bug, backport, dependencies

#3434 Update build fedora.md
  doc/build-fedora.md
Labels: documentation

#3431 Update of Polish Translation, 1.14.7
  src/qt/locale/bitcoin_pl.ts
Labels: UI

#3411 Add minor WSL building updates
  doc/build-windows.md
Labels: good first issue

#3442 1.14.7 release notes
  doc/release-notes.md
  doc/release-notes/release-notes-1.14.6.md
Labels: documentation, urgent

#3448 fixate 1.14.7 for release
  configure.ac
  src/clientversion.h
Labels: urgent
