Repository dogecoin/dogecoin, pull requests merged in 2024-08, with the labels that each got.

#3612 Update manpages for 1.14.8 release
  doc/man/dogecoin-cli.1
  doc/man/dogecoin-qt.1
  doc/man/dogecoin-tx.1
  doc/man/dogecoind.1
Labels: documentation

#3609 1.14.8 Release Notes
  doc/release-notes.md
  doc/release-notes/release-notes-1.14.7.md
Labels: documentation

#3615 Fixate 1.14.8 for release
  configure.ac
  src/clientversion.h
Labels: urgent

#3569 doc: change the branching strategy
  README.md
Labels: documentation, urgent
