Repository dogecoin/dogecoin, pull requests merged in 2024-07, with the labels that each got.

#3567 bugfix: avoid the use of abs in time data
  src/timedata.cpp
Labels: bug, backport, backport to 1.14

#3568 p2p: reduce amount of getheaders sent per inv
  src/net_processing.cpp
Labels: backport, backport to 1.14

#3565 Added pt_PT Readme
  doc/intl/README.md
  doc/intl/pt_PT/README.md
Labels: documentation

#3313 refactor: fix undefined behavior and cleanup lock debugging code
  src/Makefile.test.include
  src/sync.cpp
  src/sync.h
  src/test/sync_tests.cpp
Labels: backport, cleanup, backport to 1.14

#3572 qa: fix walletnotify test
  qa/rpc-tests/walletnotify.py
Labels: QA, backport to 1.14

#3574 qa: add getdata test
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p-getdata.py
Labels: backport, QA, backport to 1.14

#3575 net: improve orphan processing
  src/net.h
  src/net_processing.cpp
Labels: backport, cleanup, backport to 1.14

#3576 validation: avoid masking of difficulty adjustment errors
  src/validation.cpp
Labels: bug, backport, backport to 1.14

#3481 Fix: depends fail to build, bump expat version
  depends/packages/expat.mk
Labels: dependencies, backport to 1.14

#3577 backport: TxRequestTracker module
  qa/rpc-tests/p2p-tx-download.py
  src/Makefile.am
  src/Makefile.test.include
  src/limitedmap.h
  src/net.h
  src/net_processing.cpp
  src/test/limitedmap_tests.cpp
  src/test/txrequest_tests.cpp
  src/txrequest.cpp
  src/txrequest.h
  src/uint256.cpp
  src/uint256.h
  src/utilmemory.h
Labels: bug, backport, backport to 1.14

#3558 compat: fix compatibility with boost 1.85
  src/rpc/protocol.cpp
  src/util.cpp
  src/validation.h
  src/wallet/wallet.cpp
Labels: bug, dependencies, backport to 1.14

#3580 doc: simplify macOS build guide
  doc/build-macos.md
Labels: documentation

#3582 ci: pin setuptools version to 70.3.0
  .github/workflows/ci.yml
Labels: QA, backport to 1.14

#3584 1.14.8: CI fixes
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/linter.yml
Labels: backport

#3585 open 1.14.8
  configure.ac
  src/clientversion.h
Labels: urgent

#3549 Add gen-dogecoin-conf.sh from bitcoin core github
  contrib/devtools/gen-dogecoin-conf.sh
  share/dogecoin.conf
Labels: enhancement

#3588 1.14.8: enable compiling against newer boost versions
  src/Makefile.test.include
  src/bench/bench.cpp
  src/bench/bench.h
  src/bench/bench_bitcoin.cpp
  src/rpc/protocol.cpp
  src/sync.cpp
  src/sync.h
  src/test/sync_tests.cpp
  src/util.cpp
  src/validation.h
  src/wallet/wallet.cpp
Labels: backport

#3586 1.14.8: backport test fixes
  contrib/devtools/check-translations.py
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/p2p-getdata.py
  qa/rpc-tests/walletnotify.py
Labels: backport

#3589 1.14.8: allow compiling with c++17
  .github/workflows/ci.yml
  build-aux/m4/ax_cxx_compile_stdcxx.m4
  configure.ac
  src/Makefile.test.include
  src/net_processing.cpp
  src/random.h
  src/test/random_tests.cpp
  src/wallet/wallet.cpp
Labels: backport

#3592 1.14.8: Backport TxRequestTracker
  qa/rpc-tests/p2p-tx-download.py
  src/Makefile.am
  src/Makefile.test.include
  src/limitedmap.h
  src/net.h
  src/net_processing.cpp
  src/test/limitedmap_tests.cpp
  src/test/txrequest_tests.cpp
  src/txrequest.cpp
  src/txrequest.h
  src/uint256.cpp
  src/uint256.h
  src/utilmemory.h
Labels: backport

#3611 doc: add security policy with contacts
  SECURITY.md
Labels: documentation
