Repository dogecoin/dogecoin, pull requests merged in 2024-06, with the labels that each got.

#3511 backport: Use FastRandomContext for all tests
  configure.ac
  src/Makefile.am
  src/Makefile.test.include
  src/addrman.cpp
  src/addrman.h
  src/bench/checkqueue.cpp
  src/bench/crypto_hash.cpp
  src/crypto/chacha20.cpp
  src/crypto/chacha20.h
  src/crypto/common.h
  src/init.cpp
  src/net.h
  src/random.cpp
  src/random.h
  src/test/DoS_tests.cpp
  src/test/addrman_tests.cpp
  src/test/blockencodings_tests.cpp
  src/test/bloom_tests.cpp
  src/test/checkqueue_tests.cpp
  src/test/coins_tests.cpp
  src/test/crypto_tests.cpp
  src/test/cuckoocache_tests.cpp
  src/test/dbwrapper_tests.cpp
  src/test/merkle_tests.cpp
  src/test/miner_tests.cpp
  src/test/pmt_tests.cpp
  src/test/pow_tests.cpp
  src/test/prevector_tests.cpp
  src/test/random_tests.cpp
  src/test/sighash_tests.cpp
  src/test/skiplist_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/test_bitcoin.h
  src/test/test_random.h
  src/test/util_tests.cpp
  src/test/versionbits_tests.cpp
  src/wallet/test/crypto_tests.cpp
  src/wallet/wallet.cpp
Labels: enhancement, backport

#3521 backport: random.h/.cpp cherry-picks up to #10821
  src/bench/bench_bitcoin.cpp
  src/compat.h
  src/init.cpp
  src/random.cpp
  src/random.h
  src/test/random_tests.cpp
  src/test/test_bitcoin.cpp
Labels: backport

#3560 random: use std::shuffle instead of std::random_shuffle
  src/net_processing.cpp
  src/wallet/wallet.cpp
Labels: enhancement

#3557 doc: add security policy
  SECURITY.md
Labels: documentation, urgent

#3393 Add dust metrics to getblockstats
  qa/rpc-tests/data/getblockstats.json
  src/rpc/blockchain.cpp
Labels: enhancement, RPC

#3561 build: allow c++17 standard to be used for compilation
  configure.ac
Labels: enhancement

#3459 Organize internationalized documentation
  README.md
  doc/intl/README.md
  doc/intl/fa_IR/README.md
  doc/intl/pt_BR/README.md
  doc/intl/vi_VN/README.md
  doc/intl/zh_CN/README.md
Labels: documentation

#3194 Translation and addition of the README.md file in French (README_fr_FR.md)
  doc/intl/README.md
  doc/intl/fr/README.md
Labels: documentation
