Repository dogecoin/dogecoin, pull requests merged in 2024-03, with the labels that each got.

#3467 ci: update actions to v4
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/linter.yml
Labels: QA

#3473 fix some typos in comments
  src/rpc/client.cpp
  src/test/checkqueue_tests.cpp
  src/test/txvalidationcache_tests.cpp
  src/utiltime.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: documentation

#3465 build: remove qt4 from macros
  build-aux/m4/bitcoin_qt.m4
Labels: dependencies, cleanup

#3462 Remove Qt 4 ifdefs
  src/qt/addressbookpage.cpp
  src/qt/bantablemodel.cpp
  src/qt/bitcoin.cpp
  src/qt/bitcoingui.cpp
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/macdockiconhandler.mm
  src/qt/networkstyle.cpp
  src/qt/openuridialog.cpp
  src/qt/optionsdialog.cpp
  src/qt/paymentrequestplus.cpp
  src/qt/paymentserver.cpp
  src/qt/peertablemodel.cpp
  src/qt/receiverequestdialog.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsentry.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/test/test_main.cpp
  src/qt/transactionview.cpp
  src/qt/utilitydialog.cpp
  src/qt/winshutdownmonitor.cpp
  src/qt/winshutdownmonitor.h
Labels: dependencies

#3446 check numerus format in check-translations.py
  contrib/devtools/check-translations.py
Labels: enhancement, QA

#3456 bench: iwyu cleanup on non-test sources
  src/bench/bench.cpp
  src/bench/bench.h
  src/bench/bench_bitcoin.cpp
Labels: cleanup, backport to 1.14

#3479 Fix a minor formatting mistake in build-unix.md
  doc/build-unix.md
Labels: documentation

#3362 depends: updated to freetype 2.11.0
  depends/packages/freetype.mk
Labels: dependencies

#3492 ci: run experimental CIs with c++14
  .github/workflows/ci.yml
Labels: QA

#3490 net: make IteratorComparator's operator const
  src/net_processing.cpp
Labels: cleanup

#3488 backport: fs wrapper
  src/Makefile.am
  src/addrdb.cpp
  src/addrdb.h
  src/bitcoin-cli.cpp
  src/bitcoin-tx.cpp
  src/bitcoind.cpp
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/fs.cpp
  src/fs.h
  src/init.cpp
  src/net.h
  src/qt/bitcoin.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/intro.cpp
  src/qt/test/rpcnestedtests.cpp
  src/rpc/protocol.cpp
  src/rpc/protocol.h
  src/rpc/server.cpp
  src/test/dbwrapper_tests.cpp
  src/test/script_tests.cpp
  src/test/test_bitcoin.cpp
  src/test/test_bitcoin.h
  src/test/testutil.cpp
  src/test/testutil.h
  src/torcontrol.cpp
  src/util.cpp
  src/util.h
  src/validation.cpp
  src/validation.h
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcutil.cpp
  src/wallet/rpcutil.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
Labels: backport
