Repository dogecoin/dogecoin, pull requests merged in 2024-04, with the labels that each got.

#3499 rpc: add uptime (backport)
  doc/rpc-maturity.md
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/uptime.py
  src/qt/clientmodel.cpp
  src/rpc/server.cpp
  src/util.cpp
  src/util.h
Labels: enhancement, backport, RPC

#3506 fix: mising koinu string (rebrand)
  src/qt/forms/sendcoinsdialog.ui
Labels: UI

#3517 ci: update codeql to v3
  .github/workflows/codeql-analysis.yml
Labels: QA
