Repository dogecoin/dogecoin, pull requests merged in 2024-10, with the labels that each got.

#3622 German README.md
  doc/intl/de_GER/README.md
Labels: documentation, help wanted

#3623 docs: update French README
  doc/intl/fr/README.md
Labels: documentation

#3661 bugfix: change asserts into handled failures for cmpctblk
  src/blockencodings.cpp
Labels: bug, backport, backport to 1.14

#3643 readme: remove all external URLs other than our GitHub repo
  README.md
Labels: documentation

#3664 doc: fix typos
  doc/developer-notes.md
  doc/getting-started.md
  doc/init.md
Labels: documentation
